#!/usr/bin/env node
/**
 * us-fund-advisor / deliver.js
 * 读取 Claude 分析结果，格式化为飞书消息卡片并推送
 * 用法：node scripts/deliver.js [--input <path>] [--dry-run]
 */

const fs   = require("fs");
const path = require("path");
const crypto = require("crypto");

const CONFIG_PATH = path.join(__dirname, "../config.json");
const FUNDS_PATH  = path.join(__dirname, "../funds.json");
const LOG_PATH    = path.join(__dirname, "../logs/deliver.log");
const DATA_PATH   = "/tmp/us-fund-data.json";

const args    = process.argv.slice(2);
const DRY_RUN = args.includes("--dry-run");
const inputIdx = args.indexOf("--input");
const INPUT_PATH = inputIdx !== -1 ? args[inputIdx + 1] : "/tmp/us-fund-result.json";

const config = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"));
const funds  = JSON.parse(fs.readFileSync(FUNDS_PATH,  "utf8"));

function log(msg) {
  const line = `[${new Date().toISOString()}] ${msg}`;
  console.log(line);
  fs.mkdirSync(path.dirname(LOG_PATH), { recursive: true });
  fs.appendFileSync(LOG_PATH, line + "\n");
}

// ── 多语言文案 ────────────────────────────────────────────────────────────────
const I18N = {
  zh: {
    title: "📊 美股基金每日简报",
    weekday: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
    marketSummary: "市场概述",
    marketRisk: "市场风险",
    actionSummary: "今日操作摘要",
    operationGuide: "🎯 操作指导",
    macroFlags: "本周需关注",
    dataSource: "数据来源",
    keyDrivers: "关键驱动",
    signal: {
      buy:  { text: "加仓 ▲", color: "green" },
      hold: { text: "持有 —", color: "orange" },
      sell: { text: "减仓 ▼", color: "red" }
    },
    risk: {
      low:    { text: "🟢 低风险", color: "green" },
      medium: { text: "🟡 中等风险", color: "orange" },
      high:   { text: "🔴 高风险", color: "red" }
    },
    disclaimer: "⚠️ 以上内容由 AI 基于公开信息生成，仅供参考，不构成投资建议。投资有风险，操作需谨慎。",
    sourceLabels: {
      fred: "FRED（圣路易斯联储）",
      fredEmpty: "未获取到数据",
      yahoo: "Yahoo Finance",
      yahooEmpty: "行情数据获取失败",
      rss: "RSS 新闻",
      rssEmpty: "未获取到有效内容",
      twitter: "X/Twitter",
      twitterEmpty: "未配置或未获取到数据",
      akshareIndex: "AKShare / index_us_stock_sina",
      akshareStock: "AKShare / stock_us_daily",
      akshareFund: "AKShare / fund_open_fund_daily_em",
      akshareFundCount: "只开放式基金净值"
    }
  },
  en: {
    title: "📊 US Fund Daily Briefing",
    weekday: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    marketSummary: "Market Summary",
    marketRisk: "Market Risk",
    actionSummary: "Today's Action Summary",
    operationGuide: "🎯 Operation Guide",
    macroFlags: "Upcoming Macro Events",
    dataSource: "Data Sources",
    keyDrivers: "Key Drivers",
    signal: {
      buy:  { text: "Buy ▲", color: "green" },
      hold: { text: "Hold —", color: "orange" },
      sell: { text: "Sell ▼", color: "red" }
    },
    risk: {
      low:    { text: "🟢 Low Risk", color: "green" },
      medium: { text: "🟡 Medium Risk", color: "orange" },
      high:   { text: "🔴 High Risk", color: "red" }
    },
    disclaimer: "⚠️ This content is generated by AI based on public information for reference only and does not constitute investment advice. Investing involves risk; proceed with caution.",
    sourceLabels: {
      fred: "FRED (St. Louis Fed)",
      fredEmpty: "No data retrieved",
      yahoo: "Yahoo Finance",
      yahooEmpty: "Market data unavailable",
      rss: "RSS News",
      rssEmpty: "No valid content retrieved",
      twitter: "X/Twitter",
      twitterEmpty: "Not configured or no data retrieved",
      akshareIndex: "AKShare / index_us_stock_sina",
      akshareStock: "AKShare / stock_us_daily",
      akshareFund: "AKShare / fund_open_fund_daily_em",
      akshareFundCount: "open-end fund NAVs"
    }
  }
};

const SECTOR_ORDER = ["nasdaq", "gold", "semi", "ai"];

// ── 构建数据来源说明 ──────────────────────────────────────────────────────────
function buildDataSource(raw, lang) {
  const t = I18N[lang]?.sourceLabels || I18N.zh.sourceLabels;
  const lines = [];

  // FRED
  const fredKeys = Object.keys(raw.fred || {});
  if (fredKeys.length > 0) {
    const labels = fredKeys.map(k => raw.fred[k].label).filter(Boolean);
    lines.push(`• **${t.fred}**：${labels.join("、")}`);
  } else {
    lines.push(`• **${t.fred}**：${t.fredEmpty}`);
  }

  // Market
  const marketKeys = Object.keys(raw.market || {});
  if (marketKeys.length > 0) {
    lines.push(`• **${t.yahoo}**：${marketKeys.join("、")}`);
  } else {
    lines.push(`• **${t.yahoo}**：${t.yahooEmpty}`);
  }

  // RSS
  const rssFeeds = (raw.rss || []).filter(r => (r.items || []).length > 0);
  if (rssFeeds.length > 0) {
    lines.push(`• **${t.rss}**：${rssFeeds.map(r => r.source).join("、")}`);
  } else {
    lines.push(`• **${t.rss}**：${t.rssEmpty}`);
  }

  // Twitter
  const twAccounts = (raw.twitter || []).filter(t => (t.tweets || []).length > 0);
  if (twAccounts.length > 0) {
    lines.push(`• **${t.twitter}**：@${twAccounts.map(t => t.username).join("、@")}`);
  } else {
    lines.push(`• **${t.twitter}**：${t.twitterEmpty}`);
  }

  // AKShare
  if (raw.akshare) {
    const ak = raw.akshare;
    const akItems = [];
    if (ak.us?.qqq_hist) akItems.push("QQQ");
    if (ak.us?.nvda_hist) akItems.push("NVDA");
    const indexNames = ak.us?.us_indices ? Object.values(ak.us.us_indices).map(i => i.name).filter(Boolean) : [];
    const fundCount = (ak.cn?.open_fund || []).length;
    if (indexNames.length > 0) {
      lines.push(`• **${t.akshareIndex}**：${indexNames.join("、")}`);
    }
    if (akItems.length > 0) {
      lines.push(`• **${t.akshareStock}**：${akItems.join("、")}`);
    }
    if (fundCount > 0) {
      lines.push(`• **${t.akshareFund}**：${fundCount} ${t.akshareFundCount}`);
    }
  }

  return lines.join("\n");
}

// ── 构建飞书卡片 ──────────────────────────────────────────────────────────────
function buildCard(result, raw) {
  const lang     = result.language || "zh";
  const t        = I18N[lang] || I18N.zh;
  const risk     = t.risk[result.risk_level] || t.risk.medium;
  const dateStr  = result.date || new Date().toISOString().slice(0, 10);
  const weekday  = t.weekday[new Date(dateStr + "T00:00:00").getDay()];

  // 板块行
  const sectorElements = SECTOR_ORDER.map(sid => {
    const sector    = result.sectors?.[sid];
    const fundInfo  = funds.sectors[sid];
    if (!sector || !fundInfo) return null;

    const signal    = t.signal[sector.signal] || { text: sector.signal, color: "default" };
    const primary   = fundInfo.funds.find(f => f.primary) || fundInfo.funds[0];
    const sectorName = lang === "en" && fundInfo.name_en ? fundInfo.name_en : fundInfo.name;

    const drivers = (sector.key_drivers || []).map(d => `• ${d}`).join("\n");
    return {
      tag: "div",
      fields: [
        {
          is_short: true,
          text: {
            tag: "lark_md",
            content: `**${fundInfo.icon} ${sectorName}**\n<font color="${signal.color}">${signal.text}</font>\n${sector.status}`
          }
        },
        {
          is_short: true,
          text: {
            tag: "lark_md",
            content: `💡 ${sector.reasoning}\n\n**${t.keyDrivers}**\n${drivers}`
          }
        }
      ]
    };
  }).filter(Boolean);

  // 宏观标记
  const macroFlags = (result.macro_flags || []).map(f => `• ${f}`).join("\n");

  const elements = [
    // 标题栏
    {
      tag: "div",
      text: {
        tag: "lark_md",
        content: `${t.title} · ${dateStr} ${weekday}`
      }
    },
    { tag: "hr" },
    // 市场概述
    {
      tag: "div",
      text: {
        tag: "lark_md",
        content: `**${t.marketSummary}**\n${result.market_summary}`
      }
    },
    {
      tag: "div",
      text: {
        tag: "lark_md",
        content: `**${t.marketRisk}** ${risk.text}`
      }
    },
    { tag: "hr" },
    // 板块 & 基金建议（两两一行）
    ...sectorElements,
    { tag: "hr" },
    // 今日操作摘要
    {
      tag: "div",
      text: {
        tag: "lark_md",
        content: `**${t.actionSummary}**\n${result.action_summary}`
      }
    }
  ];

  // 操作指导（如果有）
  if (result.operation_guide) {
    elements.push({ tag: "hr" });
    elements.push({
      tag: "div",
      text: {
        tag: "lark_md",
        content: `**${t.operationGuide}**\n${result.operation_guide}`
      }
    });
  }

  // 宏观事件（如果有）
  if (macroFlags) {
    elements.push({ tag: "hr" });
    elements.push({
      tag: "div",
      text: {
        tag: "lark_md",
        content: `**${t.macroFlags}**\n${macroFlags}`
      }
    });
  }

  // 数据来源
  const dataSourceText = raw ? buildDataSource(raw, lang) : "";
  if (dataSourceText) {
    elements.push({ tag: "hr" });
    elements.push({
      tag: "div",
      text: {
        tag: "lark_md",
        content: `**${t.dataSource}**\n${dataSourceText}`
      }
    });
  }

  // 免责声明
  elements.push(
    { tag: "hr" },
    {
      tag: "note",
      elements: [{
        tag: "plain_text",
        content: t.disclaimer
      }]
    }
  );

  return {
    msg_type: "interactive",
    card: {
      config: { wide_screen_mode: true },
      elements
    }
  };
}

// ── 飞书签名（如果配置了 secret）────────────────────────────────────────────
function sign(timestamp, secret) {
  const str  = `${timestamp}\n${secret}`;
  return crypto.createHmac("sha256", str).digest("base64");
}

// ── 推送 ─────────────────────────────────────────────────────────────────────
async function deliver(card) {
  const webhookUrl = config.feishu?.webhook_url;
  if (!webhookUrl || webhookUrl.includes("YOUR_")) {
    log("❌ 飞书 Webhook URL 未配置，请检查 config.json");
    process.exit(1);
  }

  let body = card;
  if (config.feishu?.secret) {
    const ts    = Math.floor(Date.now() / 1000).toString();
    const sig   = sign(ts, config.feishu.secret);
    body        = { ...card, timestamp: ts, sign: sig };
  }

  const res = await fetch(webhookUrl, {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify(body)
  });

  const data = await res.json();
  if (data.code === 0 || data.StatusCode === 0) {
    log("✅ 飞书推送成功");
  } else {
    log(`❌ 飞书推送失败: ${JSON.stringify(data)}`);
    process.exit(1);
  }
}

// ── 主流程 ──────────────────────────────────────────────────────────────────
async function main() {
  if (!fs.existsSync(INPUT_PATH)) {
    log(`❌ 结果文件不存在: ${INPUT_PATH}`);
    process.exit(1);
  }

  const result = JSON.parse(fs.readFileSync(INPUT_PATH, "utf8"));
  log(`📄 读取结果文件: ${INPUT_PATH}`);

  let raw = null;
  if (fs.existsSync(DATA_PATH)) {
    raw = JSON.parse(fs.readFileSync(DATA_PATH, "utf8"));
  }

  const card = buildCard(result, raw);

  if (DRY_RUN) {
    log("🔍 Dry run 模式，不实际推送：");
    console.log(JSON.stringify(card, null, 2));
    return;
  }

  await deliver(card);

  // 保存结果备份
  const dir  = path.join(__dirname, "../logs/results");
  fs.mkdirSync(dir, { recursive: true });
  const date = (result.date || new Date().toISOString().slice(0, 10));
  fs.writeFileSync(path.join(dir, `${date}.json`), JSON.stringify(result, null, 2));
}

main().catch(e => {
  log(`❌ 致命错误: ${e.message}`);
  process.exit(1);
});
